backend:
  name: github
  repo: whosdustin/tdby
  branch: master

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: "posts"
    label: "BlogPosts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }